disabled_rules:
   - block_based_kvo
   - identifier_name
   - line_length
   - trailing_comma
   - trailing_whitespace
   - void_return

included:
# Paths relative to BuildTools. See app target "Run Script (SwiftLint)" for more information.
  - ../CoffeeKit
  - ../CoffeeKitTests
